import { existsSync, readdirSync, unlinkSync, writeFileSync } from "node:fs";
import { basename, extname, join, relative } from "node:path";
import { pathToFileURL } from "node:url";

const SUPPORTED_TOOL_EXTENSIONS = new Set([".js", ".mjs", ".cjs", ".ts", ".mts", ".cts"]);
const IGNORED_DIRECTORY_NAMES = new Set(["node_modules", ".git", "dist", "coverage"]);
export const DATA_REPO_TOOL_STUB_PREFIX = "zz-data-";

/**
 * @param {string} directoryPath
 * @returns {string[]}
 */
export function collectToolModuleFiles(directoryPath) {
  if (!existsSync(directoryPath)) {
    return [];
  }

  /** @type {string[]} */
  const collected = [];

  const visit = (currentPath) => {
    for (const entry of readdirSync(currentPath, { withFileTypes: true }).sort((left, right) =>
      left.name.localeCompare(right.name)
    )) {
      const entryPath = join(currentPath, entry.name);

      if (entry.isDirectory()) {
        if (IGNORED_DIRECTORY_NAMES.has(entry.name) || entry.name.startsWith(".")) {
          continue;
        }
        visit(entryPath);
        continue;
      }

      if (!entry.isFile()) {
        continue;
      }

      if (!SUPPORTED_TOOL_EXTENSIONS.has(extname(entry.name))) {
        continue;
      }

      if (entry.name.startsWith(DATA_REPO_TOOL_STUB_PREFIX)) {
        continue;
      }

      collected.push(entryPath);
    }
  };

  visit(directoryPath);
  return collected;
}

/**
 * @param {string} relativePath
 * @returns {string}
 */
function stubFileName(relativePath) {
  const withoutExt = relativePath.replace(/\.[^.]+$/, "");
  const safe = withoutExt
    .replace(/[^a-zA-Z0-9._-]+/g, "-")
    .replace(/-+/g, "-")
    .replace(/^-+|-+$/g, "");
  return `${DATA_REPO_TOOL_STUB_PREFIX}${safe || "tool"}.mjs`;
}

/**
 * Write host-local stub modules that re-export data-repo tools from their
 * original paths so relative imports and import.meta.url stay valid.
 *
 * @param {string} dataToolsDir
 * @param {string} hostToolsDir
 * @returns {string[]}
 */
export function generateDataRepoToolStubs(dataToolsDir, hostToolsDir) {
  const moduleFiles = collectToolModuleFiles(dataToolsDir);
  /** @type {string[]} */
  const written = [];

  for (const modulePath of moduleFiles) {
    const stubPath = join(hostToolsDir, stubFileName(relative(dataToolsDir, modulePath)));
    const source = pathToFileURL(modulePath).href;
    writeFileSync(
      stubPath,
      [
        "// Generated by oi.mjs; do not edit.",
        `// Source: ${modulePath}`,
        `export { name, tools, default } from ${JSON.stringify(source)};`,
        ""
      ].join("\n"),
      "utf8"
    );
    written.push(stubPath);
  }

  return written;
}

/**
 * @param {string[]} stubPaths
 */
export function removeGeneratedToolStubs(stubPaths) {
  for (const stubPath of stubPaths) {
    if (!existsSync(stubPath)) {
      continue;
    }
    unlinkSync(stubPath);
  }
}

/**
 * @param {string} hostToolsDir
 * @param {string | undefined} dataToolsDir
 * @returns {string[]}
 */
export function prepareDataRepoToolStubs(hostToolsDir, dataToolsDir) {
  if (!dataToolsDir || !existsSync(dataToolsDir)) {
    return [];
  }

  return generateDataRepoToolStubs(dataToolsDir, hostToolsDir);
}
